# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      BC_USER: ${{ vars.BC_USER }}
      BC_KEY: ${{ vars.BC_KEY }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Is variable exported?
        run: |
          echo "${{ vars.BC_USER }}"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: run tests against chrome_mac in browserCloud
        run: mvn clean test -Dbrowser=browserCloud -DbrowserCloudEnv=chrome_mac  -Dcucumber.filter.tags=@shadowDom

      - name: run tests against firefox_mac in browserCloud
        run: mvn clean test -Dbrowser=browserCloud -DbrowserCloudEnv=firefox_mac  -Dcucumber.filter.tags=@shadowDom